### ISSUE TITLE
Another Outlet has already registered for outlet

### ISSUE THREAD

**Issue by BrunoQuaresma** [carlsverre/react-outlet#5]
when I re-run my tests this error appears.

`Another Outlet has already registered for outlet`

How can i avoid?

**Comment by carlsverre** [comment]
Call `OutletRegistry.reset()` before running different tests.  Also as React-Outlet is currently written you can't run multiple tests concurrently unless each test has a different OutletID.

**Comment by BrunoQuaresma** [comment]
It works. Thanks!
