### ISSUE TITLE
How to include multiple times into single outlet

### ISSUE THREAD

**Issue by vlsergeyatsbt** [carlsverre/react-outlet#6]
Hi!

I'm using Outlet / Plug to include buttons from forms (middle of the screen) to top toolbar panel (at the top of the screen). It works perfectly.

However, once i tried to put second form on the screen. But it's Plug replaced Plug from first form, so i can see toolbar buttons only from second form, not both.

Is there a way to allow include multiple Plugs into single Outlet?

v.1.0.6

Best regards,
Sergey

**Comment by KenLSM** [comment]
Plugs and Outlets have a 1:1 relationship. Having multiple plugs to a single outlet violates this rule.

You could try creating another outlet for that other plug.

**Comment by vlsergeyatsbt** [comment]
But second outlet need to have another ID. Is there a way to do something like:
- get outletid from array
-- check if it is occupied already
-- if not, use it, otherwise get another outlet id

**Comment by carlsverre** [comment]
@vlsergeyatsbt sorry for the huge delay!  I added a way to check the registry to see if an Outlet ID is currently occupied.  Let me know if that solves your use-case.
